#!/bin/bash
#
#   $Id: init_script 22 2006-01-29 11:17:52Z finley $
#
#   Start or stop wifi-radar in daemon mode.
#
#   Written by Ante Karamatic <ivoks@grad.hr>
#
#   Modified by Brian Elliott Finley <brian@thefinleys.com>
#   
#   Modified by Patrick Winnertz <winnie@debian.org>
#
### BEGIN INIT INFO
# Provides:          wifi-radar
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2
# Default-Stop:      0  6
# Short-Description: Startup wifi-radar daemon
# Description:      This script startup the wifi-radar daemon which will
#                   always  look for the strongest wifi hot-spot which is
#                   known and connect to it.
### END INIT INFO


PATH=/bin:/usr/bin:/sbin:/usr/sbin
WR_BIN="/usr/sbin/wifi-radar"
ETH=`grep interface /etc/wifi-radar.conf  2>/dev/null | cut -d' ' -f3 2>/dev/null`
PIDFILE="/var/run/wifi-radar-daemon.pid"
DHCP_PID=`cat /var/run/dhcpcd-wifi.pid 2>/dev/null`

. /lib/lsb/init-functions

case "${1}" in
("start")
    vpnc-disconnect >/dev/null 2>&1
	log_begin_msg "Starting wifi-radar daemon..."
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec "${WR_BIN}" -- -d >/dev/null 2>&1 &
	exit $?
	;;
("stop")
	log_begin_msg "Stopping wifi-radar daemon..."
	start-stop-daemon --stop --retry=1 --pidfile $PIDFILE --quiet --exec "${WR_BIN}" >/dev/null 2>&1
	kill -9 $DHCP_PID >/dev/null 2>&1
        if [ ! "$ETH" = "auto_detect" ]; then
	        ifconfig "${ETH}" down >/dev/null 2>&1
        fi
	exit $?
	;;
("restart")
	"${0}" stop
	"${0}" start
	;;
("force-reload")
        "${0}" stop
        "${0}" start
        ;;
(*)
	log_success_msg "Usage: /etc/init.d/wifi-radar {start|stop|restart}" >&2
	exit 3
	;;
esac
